#!/bin/bash

./clean_outlier.py

awk '{print $43}' < clean_all_feat > clean_label_only

#awk '{print $1 " " $5 " " $6 " " $8 " " $9 " " $10 " " $11 " " $22 " " $23 " " $24 " " $25 " " $26 " " $27 " " $28 " " $29 " " $30 " " $31 " " $42}' clean_all_feat > clean_feat_only

awk '{print $1 " " $2 " " $3 " " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 " " $15 " " $16 " " $17 " " $18 " " $19 " " $20 " " $21 " " $22 " " $23 " " $24 " " $25 " " $26 " " $27 " " $28 " " $29 " " $30 " " $31 " " $32 " " $33 " " $34 " " $35 " " $36 " " $37 " " $38 " " $39 " " 40 " " $41 " " $42}' clean_all_feat > clean_feat_only

./bash_clean_awk_features
