#!/bin/bash

for filename in *.bmp; do
	name="${filename%.*}"
	./bash_master $name
done

cat *.feat > all_feat

awk '{print $43}' < all_feat > label_only
awk '{print $1 " " $2 " " $3 " " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 " " $15 " " $16 " " $17 " " $18 " " $19 " " $20 " " $21 " " $22 " " $23 " " $24 " " $25 " " $26 " " $27 " " $28 " " $29 " " $30 " " $31 " " $32 " " $33 " " $34 " " $35 " " $36 " " $37 " " $38 " " $39 " " $40 " " $41 " " $42}' all_feat > feat_only

#rm -rf *.txt1 *.txt2 *.txt3 *.png *.band *.shape *.der_poly3 *.der_poly3_ext *.feat count

./bash_awk_features
